<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ba55a62e3696',
		'title' => 'Restaurant Menu',
		'fields' => array(
			array(
				'key' => 'field_5ba939279cb26',
				'label' => 'Content',
				'name' => 'content',
				'type' => 'flexible_content',
				'instructions' => 'You may add sections to the menu by clicking the Add Section button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5ba9393920e29' => array(
						'key' => '5ba9393920e29',
						'name' => 'menu_section',
						'label' => 'Menu Section',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba55d14bc2b5',
								'label' => 'Section Header',
								'name' => 'section_header',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => 255,
							),
							array(
								'key' => 'field_5ba55d43bc2b6',
								'label' => 'Section Description',
								'name' => 'section_description',
								'type' => 'text',
								'instructions' => 'A description of the types of menu items that are in this section.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba55dcbbc2b7',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'flexible_content',
								'instructions' => 'Click the Add Menu Item to add items to this section',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layouts' => array(
									'5ba55dd7a779b' => array(
										'key' => '5ba55dd7a779b',
										'name' => 'menu_item',
										'label' => 'Menu Item',
										'display' => 'row',
										'sub_fields' => array(
											array(
												'key' => 'field_5ba93b8527261',
												'label' => 'Photo',
												'name' => 'menu_item_photo',
												'type' => 'image',
												'instructions' => 'You may upload a photo of this menu item.',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'array',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
											),
											array(
												'key' => 'field_5ba55e09bc2b8',
												'label' => 'Name',
												'name' => 'menu_item_name',
												'type' => 'text',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba55e62bc2b9',
												'label' => 'Description',
												'name' => 'menu_item_description',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba55e75bc2ba',
												'label' => 'Price',
												'name' => 'menu_item_price',
												'type' => 'number',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '$',
												'append' => '',
												'min' => '0.00',
												'max' => '',
												'step' => '.01',
											),
										),
										'min' => '',
										'max' => '',
									),
									'layout_5ba55ecabc2bb' => array(
										'key' => 'layout_5ba55ecabc2bb',
										'name' => 'menu_item_add-on',
										'label' => 'Menu Item with add-ons',
										'display' => 'row',
										'sub_fields' => array(
											array(
												'key' => 'field_5ba93c1227263',
												'label' => 'Photo',
												'name' => 'menu_item_photo',
												'type' => 'image',
												'instructions' => 'You may upload a photo of this menu item.',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'array',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
											),
											array(
												'key' => 'field_5ba55ee5bc2bc',
												'label' => 'Name',
												'name' => 'menu_item_name',
												'type' => 'text',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba55efdbc2bd',
												'label' => 'Description',
												'name' => 'menu_item_description',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba55f11bc2be',
												'label' => 'Price',
												'name' => 'menu_item_price',
												'type' => 'number',
												'instructions' => 'Leave blank if only add-ons have prices.',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '$',
												'append' => '',
												'min' => '0.00',
												'max' => '',
												'step' => '.01',
											),
											array(
												'key' => 'field_5ba55f5cbc2bf',
												'label' => 'Add-Ons',
												'name' => 'menu_addons',
												'type' => 'repeater',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'collapsed' => 'field_5ba55f77bc2c0',
												'min' => 1,
												'max' => 0,
												'layout' => 'table',
												'button_label' => 'Add another add-on',
												'sub_fields' => array(
													array(
														'key' => 'field_5ba55f77bc2c0',
														'label' => 'Label',
														'name' => 'addon_label',
														'type' => 'text',
														'instructions' => '',
														'required' => 1,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
													array(
														'key' => 'field_5ba55fadbc2c1',
														'label' => 'Price',
														'name' => 'addon_price',
														'type' => 'number',
														'instructions' => 'Leave blank if price if not different.',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '$',
														'append' => '',
														'min' => '0.00',
														'max' => '',
														'step' => '.01',
													),
												),
											),
										),
										'min' => '',
										'max' => '',
									),
									'layout_5ba9381950318' => array(
										'key' => 'layout_5ba9381950318',
										'name' => 'menu_item_variation',
										'label' => 'Menu Item with variations',
										'display' => 'row',
										'sub_fields' => array(
											array(
												'key' => 'field_5ba93bd227262',
												'label' => 'Photo',
												'name' => 'menu_item_photo',
												'type' => 'image',
												'instructions' => 'You may upload a photo of this menu item.',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'return_format' => 'array',
												'preview_size' => 'thumbnail',
												'library' => 'all',
												'min_width' => '',
												'min_height' => '',
												'min_size' => '',
												'max_width' => '',
												'max_height' => '',
												'max_size' => '',
												'mime_types' => '',
											),
											array(
												'key' => 'field_5ba9381950319',
												'label' => 'Name',
												'name' => 'menu_item_name',
												'type' => 'text',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba938195031a',
												'label' => 'Description',
												'name' => 'menu_item_description',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba938195031c',
												'label' => 'Variation',
												'name' => 'menu_variations',
												'type' => 'repeater',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'collapsed' => 'field_5ba55f77bc2c0',
												'min' => 2,
												'max' => 0,
												'layout' => 'table',
												'button_label' => 'Add another variation',
												'sub_fields' => array(
													array(
														'key' => 'field_5ba938195031d',
														'label' => 'Label',
														'name' => 'variation_label',
														'type' => 'text',
														'instructions' => '',
														'required' => 1,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
													array(
														'key' => 'field_5ba938195031e',
														'label' => 'Price',
														'name' => 'variation_price',
														'type' => 'number',
														'instructions' => '',
														'required' => 1,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '$',
														'append' => '',
														'min' => '0.00',
														'max' => '',
														'step' => '.01',
													),
												),
											),
										),
										'min' => '',
										'max' => '',
									),
								),
								'button_label' => 'Add Menu Item',
								'min' => '',
								'max' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ba9396218fbe' => array(
						'key' => 'layout_5ba9396218fbe',
						'name' => 'content_block',
						'label' => 'Content Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba9397518fbf',
								'label' => 'Editor',
								'name' => 'content_editor',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Section',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'menu',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'format',
			5 => 'send-trackbacks',
		),
		'active' => 1,
		'description' => '',
	));

endif;
